export const products = [
  {
    id: 'p1_tshirt',
    name: 'Heritage Classic T-Shirt',
    type: 'T-Shirt',
    category: 'tshirt',
    badge: 'Best Seller',
    price: 1750,
    originalPrice: 2100,
    desc: 'Heavyweight organic combed cotton with handcrafted Ceylon heritage motif',
    image: '/img/product-1-male.jpeg',
    isCouple: false,
    totalItemsCount: 1,
  },
  {
    id: 'p1_crop',
    name: 'Heritage Classic Crop Top',
    type: 'Crop Top',
    category: 'crop',
    badge: 'Trending',
    price: 1550,
    originalPrice: 1900,
    desc: 'Soft breathable cotton tailored for relaxed streetwear silhouette',
    image: '/img/product-1-female.jpeg',
    isCouple: false,
    totalItemsCount: 1,
  },
  {
    id: 'p1_couple',
    name: 'Heritage Classic Couple Set',
    type: 'Couple Package',
    category: 'couple',
    badge: 'Free Delivery',
    price: 3100,
    originalPrice: 3800,
    desc: '1 T-Shirt + 1 Crop Top. Custom sizing combination with complimentary islandwide shipping',
    image: '/img/product-1-female-white.jpeg', 
    isCouple: true,
    totalItemsCount: 2,
  },
  {
    id: 'p2_tshirt',
    name: 'Jaffna Collective T-Shirt',
    type: 'T-Shirt',
    category: 'tshirt',
    badge: 'Signature',
    price: 1750,
    originalPrice: 2100,
    desc: 'Modern streetwear cut celebrating Jaffna maritime & architectural culture',
    image: '/img/product-2-male.jpeg',
    isCouple: false,
    totalItemsCount: 1,
  },
  {
    id: 'p2_crop',
    name: 'Jaffna Collective Crop Top',
    type: 'Crop Top',
    category: 'crop',
    badge: 'Popular',
    price: 1550,
    originalPrice: 1900,
    desc: 'Elevated crop cut with ribbed crew neckline and subtle heritage print',
    image: '/img/product-2-female.jpeg',
    isCouple: false,
    totalItemsCount: 1,
  },
  {
    id: 'p3_tshirt',
    name: 'Thambapanni Reimagined T-Shirt',
    type: 'T-Shirt',
    category: 'tshirt',
    badge: 'New Season',
    price: 1750,
    originalPrice: 2100,
    desc: 'Inspired by golden Jaffna sunsets, earth tones and artisan traditions',
    image: '/img/product-3-male.jpeg',
    isCouple: false,
    totalItemsCount: 1,
  },
  {
    id: 'p3_crop',
    name: 'Thambapanni Reimagined Crop Top',
    type: 'Crop Top',
    category: 'crop',
    badge: 'Limited',
    price: 1550,
    originalPrice: 1900,
    desc: 'Minimalist statement crop top designed for tropical comfort and effortless style',
    image: '/img/product-3-female.jpeg',
    isCouple: false,
    totalItemsCount: 1,
  }
];

